export default  {
    INDEX:"INDEX",
    DISPATCH_USER:"DISPATCH_USER",
    LOGIN_USER: "LOGIN_USER",
    LOGOUT_USER: "LOGOUT_USER",
    DISPATCH_TICKET_DETAILS: "DISPATCH_TICKET_DETAILS",
    DISPATCH_PASSENGER_DETAILS: "DISPATCH_PASSENGER_DETAILS"
}